# Generated by Django 4.0.3 on 2022-03-20 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLibrary', '0007_alter_comment_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 8, 1, 16, 942762)),
        ),
    ]
