# Generated by Django 4.0.3 on 2022-03-21 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebLibrary', '0021_alter_comment_created_date_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 21, 27, 35, 117229)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 21, 27, 35, 117229)),
        ),
    ]
