# Generated by Django 4.0.3 on 2022-03-24 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebLibrary', '0023_remove_comment_ip_alter_bookreview_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='WebLibrary.comment'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 22, 5, 2, 573771)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 22, 5, 2, 573771)),
        ),
    ]
