# Generated by Django 4.0.3 on 2022-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Main'), (2, 'Moderator'), (3, 'Super')], null=True),
        ),
    ]
