# Generated by Django 4.0.3 on 2022-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Main'), ('Moderator', (('edit', 'Editing mode'), ('non-edit', 'Non-editing mode'))), (3, 'Super')], null=True),
        ),
    ]
