# Generated by Django 4.0.3 on 2022-03-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('main', 'Main'), ('Moderator', (('edit', 'Editing mode'), ('non-edit', 'Non-editing mode'))), ('super', 'Super')], max_length=100, null=True),
        ),
    ]
