# Generated by Django 4.0.3 on 2022-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('main', 'Main'), ('moderator', 'Moderator'), ('super', 'Super')], max_length=100, null=True),
        ),
    ]
