"""empty message

Revision ID: c8deda15d859
Revises: 4eeaf9bcd197
Create Date: 2022-04-15 00:27:29.791125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8deda15d859'
down_revision = '4eeaf9bcd197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('recruiter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interviews', 'users', ['recruiter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'recruiter_id')
    # ### end Alembic commands ###
